version: "3.4"
services:
  vue3_quasar_frontend:
    image: node:16-alpine
    container_name: vue3_quasar_frontend
    entrypoint: /bin/sh
    ports:
      - 3000:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true